id: PDED33340
initial_creation_type: input
source_metadata:
  title: Tulku Rigdzin Pema
  language: en
  description: 'Texts by and about Tulku Rigdzin Pema (sprul sku rig ''dzin padma,
    b. 1948), a ritual master connected with Shechen Monastery renowned for his expertise
    in stūpa construction and consecration:'
  volume:
    c3068a04840b4883ac8651e405f21971:
      title: 'Instilling Confidence and Trust: An Inventory of the Sacred Contents
        of the Jarung Khashor Stūpa'
      parent: Inventories
created_at: '2022-03-01T01:57:31.392173'
last_modified_at: '2022-03-01T01:57:31.392179'
